### ISSUE TITLE
fix some bugs in documentation and default config in loadbalancer

### ISSUE THREAD

**Issue by mauroalderete** [novafuria/server-template#4]
### Describe the bug

- [x] Wrong node in label `- "traefik.http.services.traefik.loadbalancer.myserver.port=8080"`... must to use server node instead of myserve.

- [x] Networking handle generates some errors with the current instructions, fix to handle networks successfully.

### Expected behavior

loaadbalancer for traefik works and the networking documentation doesn't have errors.

### Actual behavior

Documentation introduces bugs in the process of network configuration

### Additional context

docu suggest

```yaml
services:
  <service_name>:
    networks:
      - lain

...

networks:
  lain:
    external: true
```

and remember add

If you change the network name, you need to change the network name in the `docker-compose.yaml` file of the services that you want to deploy in the same network. Additionaly, you need edit the `./traefik/traefik.yml` file to change the network for Docker provider.

```yaml
providers:
  docker:
    network: lain
```
